### ISSUE TITLE
get-policy.yaml 缺少 auditConfigs 欄位

### ISSUE THREAD

**Issue by fbukevin** [iKala-Cloud/ops-event-generator#25]
![截圖 2022-02-22 10 43 04](https://user-images.githubusercontent.com/4548874/155057367-b344a3f4-dbbd-4f72-903f-c2aed655929f.png)

這個問題應該是因為有些(乾淨的？) project 在取得 iam policy 時的格式會缺少 `auditConfigs` 這一層..以下是同樣發生此錯誤閃退的 kyo 提供的 get-policy 內容，明顯少了 這個欄位：

```yaml
bindings:
- members:
  - serviceAccount:[648460460468@cloudbuild.gserviceaccount.com](mailto:648460460468@cloudbuild.gserviceaccount.com)
  role: roles/cloudbuild.builds.builder
- members:
  - serviceAccount:[service-648460460468@gcp-sa-cloudbuild.iam.gserviceaccount.com](mailto:service-648460460468@gcp-sa-cloudbuild.iam.gserviceaccount.com)
  role: roles/cloudbuild.serviceAgent
- members:
  - serviceAccount:[service-648460460468@compute-system.iam.gserviceaccount.com](mailto:service-648460460468@compute-system.iam.gserviceaccount.com)
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:[service-648460460468@container-engine-robot.iam.gserviceaccount.com](mailto:service-648460460468@container-engine-robot.iam.gserviceaccount.com)
  role: roles/container.serviceAgent
- members:
  - serviceAccount:[service-648460460468@containerregistry.iam.gserviceaccount.com](mailto:service-648460460468@containerregistry.iam.gserviceaccount.com)
  role: roles/containerregistry.ServiceAgent
- members:
  - serviceAccount:[648460460468@cloudservices.gserviceaccount.com](mailto:648460460468@cloudservices.gserviceaccount.com)
  role: roles/editor
- members:
  - serviceAccount:[648460460468-compute@developer.gserviceaccount.com](mailto:648460460468-compute@developer.gserviceaccount.com)
  role: roles/eventarc.developer
- members:
  - serviceAccount:[648460460468-compute@developer.gserviceaccount.com](mailto:648460460468-compute@developer.gserviceaccount.com)
  role: roles/eventarc.eventReceiver
- members:
  - serviceAccount:[648460460468-compute@developer.gserviceaccount.com](mailto:648460460468-compute@developer.gserviceaccount.com)
  - serviceAccount:[service-648460460468@gcp-sa-eventarc.iam.gserviceaccount.com](mailto:service-648460460468@gcp-sa-eventarc.iam.gserviceaccount.com)
  role: roles/eventarc.serviceAgent
- members:
  - user:[browny.lin@ikala.tv](mailto:browny.lin@ikala.tv)
  - user:[gongss@ikala.tv](mailto:gongss@ikala.tv)
  - user:[kyo.hsu@ikala.tv](mailto:kyo.hsu@ikala.tv)
  - user:[sean.hsu@ikala.tv](mailto:sean.hsu@ikala.tv)
  - user:[shuhsien.lin@ikala.tv](mailto:shuhsien.lin@ikala.tv)
  role: roles/owner
- members:
  - serviceAccount:[service-648460460468@gcp-sa-pubsub.iam.gserviceaccount.com](mailto:service-648460460468@gcp-sa-pubsub.iam.gserviceaccount.com)
  role: roles/pubsub.serviceAgent
- members:
  - serviceAccount:[service-648460460468@serverless-robot-prod.iam.gserviceaccount.com](mailto:service-648460460468@serverless-robot-prod.iam.gserviceaccount.com)
  role: roles/run.serviceAgent
etag: BwXYkk4oDxE=
version: 1
```
